In [2]:
import pandas as pd

df = pd.read_csv("Dataset/smartphone.csv")
df.head()

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,...,internal_memory,screen_size,refresh_rate,resolution,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory
0,oneplus,OnePlus Nord CE 2 Lite 5G,18999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.59,120,1080 x 2412,3,1,Android v12,64,16.0,1 TB
1,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,Exynos 1330,exynos,Octa Core,...,64.0,6.6,90,1080 x 2408,3,1,Android v13,50,13.0,1 TB
2,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,Snapdragon 750G,snapdragon,Octa Core,...,128.0,6.6,120,1080 x 2408,3,1,Android v12,50,8.0,1 TB
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.55,120,1080 x 2400,3,1,Android v12,50,16.0,1 TB
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,Dimensity 1080,dimensity,Octa Core,...,128.0,6.7,120,1080 x 2412,3,1,Android v13,108,16.0,0

In [3]:
df["processor_brand"].unique()

array(['snapdragon', 'exynos', 'dimensity', 'bionic', 'helio', 'a13',
       'unisoc', 'google', 'tiger', nan, 'sc9863a', 'qualcomm', 'no',
       'kirin', 'fusion', 'spreadtrum', 'sprd', '2\u2009gb', 'mediatek',
       'mt'], dtype=object)

In [4]:
df.isnull().sum()
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,...,internal_memory,screen_size,refresh_rate,resolution,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory
0,oneplus,OnePlus Nord CE 2 Lite 5G,18999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.59,120,1080 x 2412,3,1,Android v12,64,16.0,1 TB
1,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,Exynos 1330,exynos,Octa Core,...,64.0,6.6,90,1080 x 2408,3,1,Android v13,50,13.0,1 TB
2,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,Snapdragon 750G,snapdragon,Octa Core,...,128.0,6.6,120,1080 x 2408,3,1,Android v12,50,8.0,1 TB
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.55,120,1080 x 2400,3,1,Android v12,50,16.0,1 TB
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,Dimensity 1080,dimensity,Octa Core,...,128.0,6.7,120,1080 x 2412,3,1,Android v13,108,16.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,vivo,Vivo V3,17500,NaN,False,False,False,Snapdragon 616,snapdragon,Octa Core,...,32.0,5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,8.0,128 GB
876,lyf,Lyf Water 1,3649,NaN,False,False,False,Snapdragon MSM8939,snapdragon,Octa Core,...,16.0,5,60,1080 x 1920,1,1,Android v5.1 (Lollipop),13,5.0,32 GB
877,samsung,Samsung Galaxy J7,8990,NaN,False,False,False,Exynos 7580,exynos,Octa Core,...,16.0,5.5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,5.0,128 GB
878,huawei,Huawei Honor 6,9800,NaN,False,False,False,Kirin 920,kirin,Octa Core,...,16.0,5,60,1080 x 1920,1,1,Android v4.4.2 (KitKat),13,5.0,64 GB
879,samsung,Samsung Star 3 Duos S5222,8990,NaN,False,False,False,No 3G,no,NaN,...,NaN,3,60,240 x 320,1,Missing,NaN,3.2,NaN,32 GB

In [5]:
df['rating'].describe()

df['rating'].fillna(df['rating'].median(),inplace=True)
df.isnull().sum()

brand_name               0
model                    0
price                    0
rating                   0
has_5g                   0
has_nfc                  0
has_ir_blaster           0
processor_name          28
processor_brand         28
num_cores               10
processor_speed         24
battery_capacity        18
fast_charging            0
ram_capacity             5
internal_memory         12
screen_size              0
refresh_rate             0
resolution              36
num_rear_cameras         0
num_front_cameras        0
os                       2
primary_camera_rear      0
primary_camera_front    33
extended_memory          0
dtype: int64

In [6]:
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,...,internal_memory,screen_size,refresh_rate,resolution,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory
0,oneplus,OnePlus Nord CE 2 Lite 5G,18999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.59,120,1080 x 2412,3,1,Android v12,64,16.0,1 TB
1,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,Exynos 1330,exynos,Octa Core,...,64.0,6.6,90,1080 x 2408,3,1,Android v13,50,13.0,1 TB
2,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,Snapdragon 750G,snapdragon,Octa Core,...,128.0,6.6,120,1080 x 2408,3,1,Android v12,50,8.0,1 TB
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,Snapdragon 695,snapdragon,Octa Core,...,128.0,6.55,120,1080 x 2400,3,1,Android v12,50,16.0,1 TB
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,Dimensity 1080,dimensity,Octa Core,...,128.0,6.7,120,1080 x 2412,3,1,Android v13,108,16.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,vivo,Vivo V3,17500,77.0,False,False,False,Snapdragon 616,snapdragon,Octa Core,...,32.0,5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,8.0,128 GB
876,lyf,Lyf Water 1,3649,77.0,False,False,False,Snapdragon MSM8939,snapdragon,Octa Core,...,16.0,5,60,1080 x 1920,1,1,Android v5.1 (Lollipop),13,5.0,32 GB
877,samsung,Samsung Galaxy J7,8990,77.0,False,False,False,Exynos 7580,exynos,Octa Core,...,16.0,5.5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,5.0,128 GB
878,huawei,Huawei Honor 6,9800,77.0,False,False,False,Kirin 920,kirin,Octa Core,...,16.0,5,60,1080 x 1920,1,1,Android v4.4.2 (KitKat),13,5.0,64 GB
879,samsung,Samsung Star 3 Duos S5222,8990,77.0,False,False,False,No 3G,no,NaN,...,NaN,3,60,240 x 320,1,Missing,NaN,3.2,NaN,32 GB

In [ ]:
mapping = {
    'Octa': 8,
    'Hexa': 6,
    'Quad': 4,
    'Dual': 2
}

# This extracts the key words and maps them to numbers in one go
df['num_cores'] = df['num_cores'].str.extract('(Octa|Hexa|Quad|Dual)', expand=False).map(mapping)

df.drop(columns=['processor_name'],inplace=True)
df['processor_brand'].fillna(df['processor_brand'].mode()[0],inplace=True)
df['num_cores'].fillna(df['num_cores'].median(),inplace=True)
df['processor_speed'].fillna(df['processor_speed'].median(),inplace=True)
df['battery_capacity'].fillna(df['battery_capacity'].mode()[0],inplace=True)
df['ram_capacity'].fillna(df['ram_capacity'].median(),inplace=True)
df['internal_memory'].fillna(df['internal_memory'].mode()[0],inplace=True)
df['resolution'].fillna(df['resolution'].mode()[0],inplace=True)
df['os'].fillna(df['os'].mode()[0], inplace=True)

In [15]:
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,internal_memory,screen_size,refresh_rate,resolution,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory
0,oneplus,OnePlus Nord CE 2 Lite 5G,18999,81.0,True,False,False,snapdragon,8.0,2.2,...,128.0,6.59,120,1080 x 2412,3,1,Android v12,64,16.0,1 TB
1,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.4,...,64.0,6.6,90,1080 x 2408,3,1,Android v13,50,13.0,1 TB
2,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,snapdragon,8.0,2.2,...,128.0,6.6,120,1080 x 2408,3,1,Android v12,50,8.0,1 TB
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.2,...,128.0,6.55,120,1080 x 2400,3,1,Android v12,50,16.0,1 TB
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.6,...,128.0,6.7,120,1080 x 2412,3,1,Android v13,108,16.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,vivo,Vivo V3,17500,77.0,False,False,False,snapdragon,8.0,1.5,...,32.0,5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,8.0,128 GB
876,lyf,Lyf Water 1,3649,77.0,False,False,False,snapdragon,8.0,1.5,...,16.0,5,60,1080 x 1920,1,1,Android v5.1 (Lollipop),13,5.0,32 GB
877,samsung,Samsung Galaxy J7,8990,77.0,False,False,False,exynos,8.0,1.5,...,16.0,5.5,60,720 x 1280,1,1,Android v5.1 (Lollipop),13,5.0,128 GB
878,huawei,Huawei Honor 6,9800,77.0,False,False,False,kirin,8.0,1.7,...,16.0,5,60,1080 x 1920,1,1,Android v4.4.2 (KitKat),13,5.0,64 GB
879,samsung,Samsung Star 3 Duos S5222,8990,77.0,False,False,False,no,8.0,2.2,...,128.0,3,60,240 x 320,1,Missing,Android v11,3.2,NaN,32 GB

In [16]:
df['num_cores'].unique()
df.isnull().sum()

brand_name               0
model                    0
price                    0
rating                   0
has_5g                   0
has_nfc                  0
has_ir_blaster           0
processor_brand          0
num_cores                0
processor_speed          0
battery_capacity         0
fast_charging            0
ram_capacity             0
internal_memory          0
screen_size              0
refresh_rate             0
resolution               0
num_rear_cameras         0
num_front_cameras        0
os                       0
primary_camera_rear      0
primary_camera_front    33
extended_memory          0
dtype: int64

In [19]:
df.to_csv('Dataset/new_phone.csv',index=False)

In [1]:
import pandas as pd

df = pd.read_csv("Dataset/new_phone.csv")

df = df.drop(columns=["primary_camera_rear","primary_camera_front"])

df.isnull().sum()

brand_name           0
model                0
price                0
rating               0
has_5g               0
has_nfc              0
has_ir_blaster       0
processor_brand      0
num_cores            0
processor_speed      0
battery_capacity     0
fast_charging        0
ram_capacity         0
internal_memory      0
screen_size          0
refresh_rate         0
resolution           0
num_rear_cameras     0
num_front_cameras    0
os                   0
extended_memory      0
dtype: int64

In [2]:
df.to_csv("Dataset/final_phone.csv",index=False)